PROGRAM MaterialExtraction
VAR
	consumptionMeterLogic : meConsumption;

	feederPumpControlLogic : meFeederPumpControl;
END_VAR


// **********************************************************************
// ** VERSION 1.0.0 - Aaron 29/01/23**
// Carries out Material Extraction logic
//
// Changelog:
// - Added ME flowmeter
// **********************************************************************

consumptionMeterLogic();
feederPumpControlLogic();

